---
- name: Install MySQL packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - 'mysql-server'
    - 'libmysqlclient-dev'

- name: Install percona-toolkit packages
  apt:
    name: percona-toolkit
    state: present
